def story():
    say = lambda word: input(word)
    print("-" * 25)
    say("Hey pal, wanna know a story?")
    say("Come a little closer..")
    say("You see...")
    say("I was just jacking it off to some porn and guess what?!")
    say("I came across a video with a woman in it.")
    say("A FUCKING WOMAN.")
    say("I inmediately knew this was the doing of those damn SJWs trying to force diversity into my entertainment...")
    say("I could feel my masculinity decrease by the second so i clicked away and searched for a video with big sweaty strong men ramming their hips against each others round toned buttocks.")
    say("Like every respectable man should dammit!")
    say("I just can't anymore.")
    say("First they invade my films and now my porn?")
    say("No, i won't let them.")
    say("I declare war on every SJW out there.")
    say("From now on i will exclusively jack off to porn with white male protagonists, and i urge you to do the same. That will teach them!!!")
    print("-" * 25) 
